name: Build icons

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - "svg/**"
      - "scripts/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "package-lock.json"
  workflow_dispatch:

concurrency:
  group: build-icons-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          if [ -f pnpm-lock.yaml ]; then
            npm i -g pnpm && pnpm i --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Build
        run: npm run build

      - name: Commit build artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: build icons"
          file_pattern: |
            png/**
            index.json
            index.color.json
            index.mono.json
            svg/**
